void _puts_recursion(char *s);
int size(char *a, int count);
void _print_rev_recursion(char *s);
int arr_adder(char array [], char old_array[], int size, int count);
int _strlen_recursion(char *s);
int factorial(int n);
int fact(int n);
int _pow_recursion(int x, int y);
int power(int x, int y, int x_init);
void reverse(int size, char *arr);
int is_prime_number(int n);
int divisors(int n, int m);
int _sqrt_recursion(int n);
int _sqrt(int n, int i);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
